import type { Metadata } from "next";
import "./globals.css";

import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-[200vh] bg-white">
        <nav className="flex items-center gap-3 fixed top-5 left-5">
          <Link
            href={"https://github.com/Rezazare76/react-modal"}
            target="_blank"
            title="Rezazare76 github"
          >
            <Image
              src="/github-mark.svg"
              alt="github icon"
              width={30}
              height={30}
            />
          </Link>
          <Link
            href={"https://www.linkedin.com/in/rezazare76"}
            target="_blank"
            title="Rezazare76 linkedin"
          >
            <Image
              src="/linkedin.svg"
              alt="linkedin icon"
              width={30}
              height={30}
            />
          </Link>
          <Link
            href={
              "https://medium.com/@rezazare2088/react-nextjs-modal-tutorial-ccc2a8ab9af8"
            }
            target="_blank"
            title="Rezazare76 medium"
          >
            <Image src="/medium.svg" alt="medium icon" width={30} height={30} />
          </Link>
        </nav>

        {children}
      </body>
    </html>
  );
}
